### ISSUE TITLE
Add support for SCT normalization

### ISSUE THREAD

**Issue by deevdevil88** [carmonalab/STACAS#17]
Hi,
I am having trouble running IntegrateData.STACAS since the latest update. Im running it for SCT normalisation method and i keeping getting the following error
`
Error in SampleIntegrationOrder(tree = slot(object = reference.integrated,  : 
  could not find function "SampleIntegrationOrder"
`
This happens regardless of the standard or the semi-supervised approach. Any ideas of what might be causing this?

Thanks
Devika

**Comment by deevdevil88** [comment]
Hi @mass-a 
I see! Indeed previously we were just using the Seurat's own integrateData function. Do you have any idea when you will be updating the STACAS  integration for SCT normalisation? I assumed it was working as the documentation for the function ncluded an argument with SCT as an option.  Perhaps you can add a note in the documentation for the function till the SCT branch is implemented so other users don't get confused like me .
I will try this with the nirmalisedata function. It's just as this halfway through my analysis and my first analysis was done with SCT in STACAS I wanted to be uniform throughout.

Thanks
Devika

**Comment by mass-a** [comment]
You are right, we should remove SCT from the normalization options, as long as this is not supported. I'll write back here if/when we implement the SCT strategy within STACAS.

Thanks!
-m

**Comment by lucygarner** [comment]
Thanks @mass-a, would be great to know when the SCT strategy has been implemented in STACAS.

**Comment by mass-a** [comment]
FYI the latest version of STACAS takes any valid assay (`assay` parameter, or the default assay) as input to `FindAnchors.STACAS()`, as well as to the `Run.STACAS()` wrapper. So you should be able to integrate data that was normalized in principle with any transformation, including SCT.

Best
-m

**Comment by CodingKaiser** [comment]
Are there any issues you foresee using the SCT assay rather than the usual RNA assay for running STACAS?

**Comment by mass-a** [comment]
Hi, in principle you should be able to apply any normalization of your choice prior to STACAS integration. One thing to note though, we did not implement a specific integration procedure based on pearson residuals as in [Seurat](https://satijalab.org/seurat/articles/sctransform_v2_vignette), so the SCT assay will not be treated any differently than any other assay.
In my personal experience I have not seen a clear advantage in using SCT compared to a simple log1p normalization (see also discussions [here](https://www.biorxiv.org/content/10.1101/2022.05.06.490859v1.full) and [here](https://doi.org/10.1093/bioinformatics/btab450)), but I'm open to be convinced otherwise :)
-m
