### ISSUE TITLE
Integrating using STACAS and Seurat

### ISSUE THREAD

**Issue by msalaciak** [carmonalab/STACAS#9]
Hi, 
firstly, I want to say what an excellent tool thank you!

I have a question regarding the Integrating scRNA-seq data using STACAS and Seurat3 vignette. You remove mito/ribo/cell cycle genes from the actual expression matrix. I wanted to know if you had tried just regressing it out as shown via SCT in seurat.

Do you recommend when working with T cell populations to remove mito/ribo/cell cycle genes?

Best,
M

**Comment by sjcarmona** [comment]
Hi, thanks for your feedback

We don't remove genes from the expression matrix but from the list of selected features (i.e. **var.features**) used for dimensionality reduction, to identify integration anchors, etc.

Ideally, such a list should contain the most informative genes to discriminate biologically relevant clusters/subtypes/states in your data (optimal number of genes might increase with data complexity). Because mito/ribo/heat shock genes are largely affected cell quality (technical) they are not great to discriminate subtypes, so we don't consider them in the variable features selection step. We also recommend ignoring cell cycle genes (which provide no subtype-specific information) and in the case of T cells, TCR genes.  

Now, in addition to that, regressing out might help you mitigate more profound effects of eg cell cycle beyond cell cycle genes. But it might also affect different subtypes in unexpected and undesirable ways (e.g. some subtypes proliferate more than others), so without a case-by-case systematic evaluation, we prefer not to regress out.

If you have a different experience we are happy to discuss!

Best,

Santiago

**Comment by msalaciak** [comment]
Thanks for the super informative answer!
